### ISSUE TITLE
Change notification sound

### ISSUE THREAD

**Issue by russell-phillips** [FossifyOrg/Messages#101]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I would like to be able to set a different notification sound.

### Why do you want this feature?

I find it useful to have a distinct sound for text messages, as they are often important.

**Comment by Aga-C** [comment]
What do you exactly mean?
- Having an ability to set different notification sounds for MMS and SMS messages? (as per Why do you want this feature)
- Having an ability to set different notification sounds for different conversations? (as per Feature description)
- Having an ability to generally change notification sound? (as per Title)

**Comment by russell-phillips** [comment]
Apologies for not being clearer. I just want to be able to generally change the notification sound.

**Comment by Aga-C** [comment]
What Android version are you using? Because this function already exists, but requires at least Android 8.

**Comment by russell-phillips** [comment]
Android 12, but I couldn't see anything in settings to set notification sound.

**Comment by naveensingh** [comment]
@russell-phillips 

Here's how:
- Open a conversation 
- Tap on the three-dot menu in the top-right corner 
- Tap on `Conversation details` option
- Tap on `Enable custom notifications` 
- Click `Customize notifications` to customize notification sound (among other things) for the selected conversation.

**Comment by russell-phillips** [comment]
Thanks, but that's per contact. Is there no way to change the notification sound for all messages? That's what I'm wanting.

**Comment by naveensingh** [comment]
Go to App settings -> Customize notifications -> Received SMS -> Sound

**Comment by russell-phillips** [comment]
App settings -> Customize notifications takes me to this screen.
![Screenshot_20240217-130556_Settings](https://github.com/FossifyOrg/Messages/assets/8222297/d35777de-7bdc-4dd2-8186-31ec22cb97ec)

**Comment by naveensingh** [comment]
On Samsung phones, you have to click on `Notification categories` to find the notification channels used by an app. You'll find "Received SMS" in there.

**Comment by russell-phillips** [comment]
Got it! Thank you for your patience :)
