### ISSUE TITLE
going back after sending a message should return to main page instead of contacts list

### ISSUE THREAD

**Issue by e075e** [FossifyOrg/Messages#106]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

eOS 1.19 (android 13)

### Affected device model

Samsung a52

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

# steps to reproduce

1. From main page, press +
2. Choose a contact
3. Write a message
4. Send it
5. Press back button

### Expected behavior

Since the user already sent a message to the contact, back button should bring to the main page

### Actual behavior

Back button brings you to the contacts list

### Additional information

As far as I know, no other conversation apps has this behavior

**Comment by Aga-C** [comment]
It's related to https://github.com/FossifyOrg/Messages/issues/80.

**Comment by Aga-C** [comment]
I've found that https://github.com/FossifyOrg/Messages/issues/80, while having more complicated reproduction steps, is about the same problem, so I close this as a duplicate. Sorry for telling you to create it.
