### ISSUE TITLE
Allow usage without being the default SMS/MMS/RCS application.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [FossifyOrg/Messages#109]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I'd like to be able to use this alongside other SMS/MMS/RCS applications.

### Why do you want this feature?

In order to evaluate its abilities and more importantly, use some of its functionality to supplement others' and vice versa.

### Additional information

See https://xdaforums.com/t/how-to-write-to-sms-content-provider-in-android-kitkat-without-being-default-sms-app.2551072/post-48032696 per https://stackoverflow.com/a/20434604/9731176.

**Comment by Aga-C** [comment]
On Android, only one app can have permission to access SMS at the time. Even if there were any hacks to avoid it, we don't want to do this, to not perform any actions that can be considered malicious, what may lead to get banned on e.g. Google Play.

**Comment by inson1** [comment]
@RokeJulianLockhart newest comment there is 1,25 year old and second newest comment is 4,25 year old and it has status "Won't fix (Obsolete)"

**Comment by RokeJulianLockhart** [comment]
> https://github.com/FossifyOrg/Messages/issues/109#issuecomment-1955187727

@inson1, I'm aware.

**Comment by MulverineX** [comment]
> actions that can be considered malicious

@Aga-C 

Otherwise known as, trying to break Google's monopolistic behavior. Gotta love when corporations label proconsumer monopoly breaking attempts at malicious behavior.
