### ISSUE TITLE
"Take Photo" option opens Lineage camera app but doesn't attach photo

### ISSUE THREAD

**Issue by mddvul22** [FossifyOrg/Messages#119]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Lineage 20

### Affected device model

Fairphone 4 and Google Pixel 3

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open Fossify SMS Messenger
2. Select a person to send a message to.
3. Tap the "+" sign and select "Take Photo"
4. The _new_ stock Lineage 20 camera app opens.
5. Take the photo.  
6. You are left with a screen that shows the photo that you have taken.  There is nothing "tappable" and you can't do anything to add the photo to Fossify SMS Messenger.
7. If I select the back button, I am taken back to the messenger app, but the photo is not attached.

### Expected behavior

I would expect that the photo would be added to my message.

### Actual behavior

The newly taken photo is not added to my message.

### Screenshots/Screen recordings

https://streamable.com/71xo7j

### Additional information

I do know that that Lineage 20 has replaced the old stock camera app with a new camera app.  I don't know if this is relevant, or not.

**Comment by Aga-C** [comment]
It's a bug in your camera app, not in Fossify Messages. When a photo is taken, your camera app should display two buttons - accept and cancel. You should raise this problem to LineageOS.

**Comment by mddvul22** [comment]
Ok, thank you.
