### ISSUE TITLE
No pop-up notification in silent mode

### ISSUE THREAD

**Issue by WebworkrNet** [FossifyOrg/Messages#122]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 14 / UI version 6.0

### Affected device model

Samsung Galaxy A13 5G (SM-A136B/DSN)

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. The notifications are activated.
2. The alerts are muted.

### Expected behavior

Pop-ups are permitted.

### Actual behavior

The "Pop-up" option is not available. 

If my memory serves me correctly, in previous SimpleMobile versions the combination of mute and pop-up was possible at the same time.

### Screenshots/Screen recordings

![Screenshot_20240302_175634_Settings](https://github.com/FossifyOrg/Messages/assets/43509007/c704cddf-7494-46e3-9295-d6a15bc42e99)

![Screenshot_20240302_175659_Settings](https://github.com/FossifyOrg/Messages/assets/43509007/30d48fb3-9f7d-418a-aaae-26cb446f0c0a)

### Additional information

I pointed out this error to the old maintainer in an email in spring 2023. After details were clarified, he said they wanted to take a look. Only later did I find the SimpleMobilesTools repository for it. However, I have not found a suitable issue, nor has the error been fixed to date. I'm afraid my report has been lost.

**Comment by Aga-C** [comment]
Can you do that for notifications in other apps? It seems more like a system issue, not an app issue.

**Comment by WebworkrNet** [comment]
Yes, it also affects other apps, as I discovered before you asked. The cause is probably the Android operating system. I agree.

**Comment by WebworkrNet** [comment]
I reported the phenomenon as a bug / feature request to Samsung.
