### ISSUE TITLE
option to show only mobile phone numbers

### ISSUE THREAD

**Issue by e075e** [FossifyOrg/Messages#127]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

An option to show only mobile phone numbers

### Why do you want this feature?

Improving workflow when sending SMS to a contact that has both a mobile and landline number

Is sending SMS to landline numbers really used?

**Comment by Aga-C** [comment]
Anybody can set any number under any field, so we can't filter out any specific field. Also, some carriers allow sending text messages to landline numbers, e.g. https://www.verizon.com/support/text-to-landline-faqs/.
