### ISSUE TITLE
Request Feature: Mute conversation

### ISSUE THREAD

**Issue by sudoshindo** [FossifyOrg/Messages#132]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When enabled for a specific conversation, no notifications will be generated from it, but messages are kept (not deleted like the Blocked Numbers/Keywords).

### Why do you want this feature?

I want to mute specific conversations because they are not very important, but I don't want to completely ignore them either.

I do not want notifications for them but I still want to see them in my conversation list.

If I block the number I will be unable to view any messages.

**Comment by Aga-C** [comment]
It's already possible via notification settings. Create custom notifications for the conversation and just set them there to not be shown.

**Comment by sudoshindo** [comment]
> It's already possible via notification settings

Are you sure about that?

![out](https://github.com/FossifyOrg/Messages/assets/97193233/3031a696-920f-49e8-8dfc-e328950916c6)

**Comment by Aga-C** [comment]
Yes, I'm sure, because I developed this feature. Open the conversation -> tap three dots menu -> `Conversation details` -> `Enable custom notifications`.

**Comment by sudoshindo** [comment]
that's what you meant not the notifications through the app info page

**Comment by sudoshindo** [comment]
sorry
thank you
