### ISSUE TITLE
Rich Communication Services (rcs) support like in google messages app

### ISSUE THREAD

**Issue by ahmadkakarr** [FossifyOrg/Messages#133]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

**The Future of Texting**: RCS is a communication protocol designed to be the supercharged successor to classic SMS and MMS. It aims to modernize the basic messaging experience on your phone.

Carrier-Based, But With Modern Features: Unlike apps like WhatsApp or Signal that rely entirely on the internet, RCS operates through your mobile carrier. However, it brings many of the features we love in internet-based messaging platforms.

Think of it as "SMS 2.0": RCS fundamentally enhances what you can do within a standard text messaging conversation.

### Why do you want this feature?

**Enhanced Messaging**: Send high-resolution photos and videos, share larger files, and enjoy a more visually appealing experience.
**Interactive Feature**s: See typing indicators, get read receipts to know when messages are seen, and easily manage group chats (adding/removing, naming).
**Brand Verification**: Businesses can use RCS to send verified messages, building trust with customers and reducing spam risks.
**In-App Actions:** Complete actions like booking appointments, making payments, or getting customer service support directly within the messaging interface.
**Wi-Fi and Data Support**: RCS works seamlessly over both mobile data and Wi-Fi connections.
**Security:** Many RCS implementations support end-to-end encryption, safeguarding message privacy.

### Additional information

https://github.com/android-rcs/rcsjta

https://developers.google.com/business-communications/rcs-business-messaging/guides/get-started/how-it-works

**Comment by Aga-C** [comment]
See: https://github.com/FossifyOrg/Messages/discussions/34.
