### ISSUE TITLE
transmission report

### ISSUE THREAD

**Issue by yusufsunetci** [FossifyOrg/Messages#145]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When we send a message, we see the sent report in the details. We should also be able to see the transmitted report.

### Why do you want this feature?

I want to know if the message we sent was transmitted to the other person or not.

**Comment by Aga-C** [comment]
There are multiple requests. Please split it into separate issues.

**Comment by yusufsunetci** [comment]
I split it.

**Comment by Aga-C** [comment]
That's not possible, see here: https://github.com/FossifyOrg/Messages/issues/126. There's also a feature request for artificially bypassing that limitation: https://github.com/FossifyOrg/Messages/issues/130.

**Comment by yusufsunetci** [comment]
> That's not possible, see here: #126.

It's not same. It's possible. I don't want to see reading. I want to know that it has been transmitted. 

For example, the message will be sent from me. The sent report will arrive. But if his phone is turned off, it will not be transmitted. The transmitted report will not arrive. Whenever he open his phone, then the transmitted report will arrive. Also, the report does not come in. It appears in the details.

This is already a feature in almost all sms applications.

You can study this: https://github.com/octoshrimpy/quik/

**Comment by Aga-C** [comment]
So it's a duplicate of https://github.com/FossifyOrg/Messages/issues/56.

**Comment by yusufsunetci** [comment]
> So it's a duplicate of #56.

I use translation for both writing and reading. So sometimes I can't understand and I can't explain.

If you understand what I'm talking about and the two topics are the same, there's no problem. :) I didn't quite understand the other issue.

Otherwise, I examined all the topics one by one before opening a new topic.

**Comment by Aga-C** [comment]
@yusufsunetci Ok, no problem :)
