### ISSUE TITLE
Deleting one message causes another arbitrary message to be deleted

### ISSUE THREAD

**Issue by tom93** [FossifyOrg/Messages#148]
**Proposed fix:** #149.

### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 14

### Affected device model

Emulator

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

(See screen recording for demo)
1. Use a clean phone with no messages to avoid deleting important messages and to be able to reproduce this reliably.
2. Create a conversation with 555-0101 and send two SMS's: "Message 1" and "Message 2".
3. Create a conversation with 555-0102 and send an SMS: "Message 3".
4. Delete "Message 3".
5. Switch to the conversation with 555-0101.

### Expected behavior

There should still be two SMS's there ("Message 1" and "Message 2").

### Actual behavior

"Message  2" is deleted (!)

### Screenshots/Screen recordings

https://github.com/FossifyOrg/Messages/assets/5887562/9833d435-5c2c-4bb9-8f62-a8a07d90d433

(the end got clipped a little, you may need to pause to see that Message 2 disappears)

### Additional information

**Workaround: DO NOT DELETE MESSAGES**

**Cause:** Commit 44c540b96187d02435b4ad2eccfbace1e2116a27 introduced a hack to update the conversation snippet, however there is a bug in that code: it tries to delete by thread ID, but the condition is applied to the SMS table, not to the threads table ([Android source](https://android.googlesource.com/platform/packages/providers/TelephonyProvider/+/android14-release/src/com/android/providers/telephony/MmsSmsProvider.java#1405)).
So instead of deleting the thread with that ID, it deletes whichever SMS happens to have that ID.

**Proposed solution:** ~~I haven't tested this yet, but~~ I believe changing the condition to "1=0" will fix the issue (it will still cause the [threads to be updated](https://android.googlesource.com/platform/packages/providers/TelephonyProvider/+/android14-release/src/com/android/providers/telephony/MmsSmsProvider.java#1409) but won't delete anything). *Update:* I've tested it using the steps above and it seems to work fine, but additional testing would be welcome.

**CC:** @Aga-C

**Comment by tom93** [comment]
It might be possible to recover unintentionally-deleted messages using the Room DAO cache, I'm not sure how easy/reliable that would be.

Either way, I think my proposed fix (#149) should be merged and released ASAP (I don't think it will interfere with potential future recovery efforts).

**Comment by Aga-C** [comment]
@naveensingh I was able to reproduce it after the fresh install of the app with no SMS messages on the phone yet. With more messages, maybe either I didn't notice or the IDs were already so high that nothing got removed.

I've also checked, no one reported it in Simple SMS Messenger, but the code has been there since 2021.

**Comment by tom93** [comment]
> With more messages, maybe either I didn't notice or the IDs were already so high that nothing got removed.

For reference, when there are many existing messages, the behaviour I'm predicting is that if you delete a message from the _i_-th oldest conversation, it will also delete the _i_-th oldest message (which might be in a different conversation). So in general it will be the oldest messages that get unintentionally deleted, and the unintentional deletion will only occur for the first deletion within each conversation. So to maximise the chances of discovery, the process would be:
1. Make a note of the oldest message(s) in each conversation.
2. Delete one message from each conversation (e.g. the most recent message).
3. Check if the oldest messages still exist.
(Obviously back up the messages first! Personally I wouldn't attempt this on a device with important messages, even with a backup.)
