### ISSUE TITLE
Bug while changing theme

### ISSUE THREAD

**Issue by krishna8755** [FossifyOrg/Messages#155]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 10

### Affected device model

Samsung Galaxy M21

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open Fossify Messages app
2. Go to settings
3. Then, to customize colors
4. Change theme to custom
5. Change background color to some other color

### Expected behavior

The background theme should have been change to user specified color

### Actual behavior

Background remains the default and theme changes to Auto Light/dark

### Screenshots/Screen recordings

https://github.com/FossifyOrg/Messages/assets/138577902/5c11e2d1-dea4-4089-9cb6-6d1d7e0d91d2

**Comment by Aga-C** [comment]
This issue affects all apps, so please raise it in https://github.com/FossifyOrg/General-Discussion/issues.
