### ISSUE TITLE
Changing the background colour of the received messages does not change the colour of the links

### ISSUE THREAD

**Issue by NickAndreou** [FossifyOrg/Messages#157]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

All versions 

### Affected Android/Custom ROM version

All

### Affected device model

All

### How did you install the app?

None

### Steps to reproduce the bug

Change color of received messages to blue.

### Expected behavior

Colour of links should be always a contrasting colour to the background. Once you give the option to change the background, links should be automatically changed to a contrasting colour.

### Actual behavior

Links stay always default blue.

### Additional information

Someone could say this is a feature request but in fact it is a design mistake that translates into a crippled interface, something that should have been tested and has not been, so technically it's a bug.

**Comment by Aga-C** [comment]
Are you sure, you are using Fossify Messages? Because it's not possible to change the background color of received messages. And links aren't always blue, they have the theme's primary color.
