### ISSUE TITLE
[ Feature Request ] Add auto-reply with SMS feature in case a call is blocked

### ISSUE THREAD

**Issue by jayb-g** [FossifyOrg/Messages#158]
Background:
I'm aware that fossify messages has a feature to manage blocked numbers from non-contacts(unknown) and manual blacklist with wild card support. But not sure if this works also for calls even if fossify dialer is not installed and user is using default stock dialer and fossify messages only. Hopefully it does. 

Feature Description:
Given what is already implemented in the app, I'm assuming this wouldn't take a lot of time and efforts of the developers and this is probably very useful feature to have, especially for those who are getting a lot of spam calls and use blacklist and/or blocks unknown numbers while understanding that practically everyone needs to receive legitimate unknown calls every now and then (eg deliveries/taxi/repairmen etc)

Taking this into consideration, if a feature would allow users to set auto-reply to calls that are blocked(whether due to being unknown or through blacklist) to make blocked callers aware of why they are blocked(eg I have blocked unknown numbers) and followup(eg ask them to reply with purpose of their call). 

(Side note: AFAIU there is a single common block list which is shared by all the dialer and SMS apps. I can see the same blocked list in both default dialer and fossify messages blocked list)

In order for this to work, there also have to be a toggle to only block calls for such numbers and not SMS. As the default AOSP dialer shows under settings > Blocked numbers, that _You won't receive calls or texts from blocked numbers_. But fossify messages has a separate toggle to _Block messages from not stored contacts_, so I'm not sure if that's in conflict and if it works as expected. 

Device: P7
OS: AOSP 14 (latest)
Fossify messages version: 1.0.1

**Comment by Aga-C** [comment]
It seems to be another case for this issue: https://github.com/FossifyOrg/Phone/issues/4.

**Comment by jayb-g** [comment]
@Aga-C sorry I'm not getting template when creating a new issue from octodroid client(while for most other repos it does show template)
