### ISSUE TITLE
Option to copy part of a text message, not the whole text. 

### ISSUE THREAD

**Issue by Densh0** [FossifyOrg/Messages#166]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Hello, could you please add an option to copy just part of a text message. Currently if you select a message it will copy the whole thing. Thank you. 

### Why do you want this feature?

Sometimes I need to copy part of a text, like a tracking number etc.

**Comment by Aga-C** [comment]
You can copy a fragment of text by long pressing the message → three dots menu → `Select text`.
