### ISSUE TITLE
replies to groups send individually 

### ISSUE THREAD

**Issue by jgilmore** [FossifyOrg/Messages#168]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 11, RPCS31.Q2-109-16-26

### Affected device model

moto stylus 2021

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Receive group message
2. Reply
3. Reply goes to each member of group individually, rather than to the group.

### Expected behavior

Reply should go to the group and show up in the group rather than as a individual text to each member of the group.

### Actual behavior

Reply shoes up in everyone else's phone as as private message from me, and not associated with the group.

### Additional information

This isn't a one time thing, nor a one carrier thing. The same behavior shows up for group members on iphone and android and various Carriers.

**Comment by naveensingh** [comment]
@jgilmore 

Please check `Settings -> Send group messages as MMS`. It is disabled by default.

**Comment by Aga-C** [comment]
https://github.com/FossifyOrg/Messages/issues/50
