### ISSUE TITLE
Mark all read

### ISSUE THREAD

**Issue by AndyM48** [FossifyOrg/Messages#186]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I would like a simple way to mark all messages as read. 

### Why do you want this feature?

I receive a large number of notifications/security alerts/passcodes and would like a simple method to mark them all as read. At present I need to:

Long press a message
select menu > Select All
select menu > Mark as Read

or:

Long press the first unread message
select each unread message individually
select menu > Mark as Read

Even then selecting Mark as Read or Mark as Unread does not always work and/or is not immediately activated

### Additional information

One possible way would be to expand the "About" menu to include some useful commands which could be quickly applied, Mark All Read being one of them.

**Comment by Aga-C** [comment]
> Even then selecting Mark as Read or Mark as Unread does not always work and/or is not immediately activated

The way you're doing this is ok, I wouldn't add any additional action. The process just takes some time, that's why it's not instantly changing the state, but it works. It could be just another case for https://github.com/FossifyOrg/General-Discussion/issues/120.
