### ISSUE TITLE
Alphanumeric sender ID should not be treated as unknown contact (not stored contact)

### ISSUE THREAD

**Issue by sudoshindo** [FossifyOrg/Messages#187]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 11

### Affected device model

Nokia G10

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

Settings > Manage blocked numbers > Blocked messages from not stored contacts (enabled)

### Expected behavior

I can still receive messages from *Alphanumeric sender IDs*.

### Actual behavior

*Alphanumeric sender IDs* get blocked.

### Screenshots/Screen recordings

**THIS IS WHAT I MEAN BY ALPHANUMERIC SENDER ID**

![Screenshot_20240707-063747](https://github.com/FossifyOrg/Messages/assets/97193233/c86ae3fa-e0b9-42b8-87bb-c0d245296edc)

### Additional information

**REASONING:**

Sometimes numbers like these are used by big brands and big tech companies to send important service announcements or even OTPs (one-time pins/passwords).

I installed this app to help an elderly family member avoid seeing spam/phishing SMS after they got scammed by one. They came to me one day confused why they weren't receiving a reply from a service they were interacting with.

Turns out this feature was blocking those messages.

**Comment by sudoshindo** [comment]
**NOTE:**

- `isAlphanumericSender` is a made up variable, I have no knowledge of Android APIs and development
- putting the check here means that the user can still use keywords to block certain marketing and promotions

```kt
if (context.baseConfig.blockUnknownNumbers) {
    val simpleContactsHelper = SimpleContactsHelper(context)
    simpleContactsHelper.exists(address, privateCursor) { exists ->
 
        // check for alphanumeric sender here (SmsReceiver.kt)
        // if contact exists or alphanumeric, handle message
        if (exists || isAlphanumericSender) {
            handleMessage(context, address, subject, body, date, read, threadId, type, subscriptionId, status)
        }
 
    }
} else {
    handleMessage(context, address, subject, body, date, read, threadId, type, subscriptionId, status)
}
```

**Comment by Aga-C** [comment]
This option blocks numbers not saved in contacts, and it did its job. Just because someone bought a short code with letters, we shouldn't automatically treat this number as a contact. Phishing could also be done this way.

**Comment by sudoshindo** [comment]
> I installed this app to help an elderly family member avoid seeing spam/phishing SMS after they got scammed by one. They came to me one day confused why they weren't receiving a reply from a service they were interacting with.

@Aga-C Did you not understand why this is a problem? There is legitimate reason for this behavior to be problematic.

Also I don't see a way to add these IDs to your contacts as a workaround. The app hides the Add Contact button for threads involving these senders.

**Comment by Aga-C** [comment]
> Also I don't see a way to add these IDs to your contacts as a workaround. The app hides the Add Contact button for threads involving these senders.

You can add to contacts by long pressing the thread on the conversation list.
