### ISSUE TITLE
[Feature Request] Add Fossify SMS Messenger to F-Droid

### ISSUE THREAD

**Issue by jahway603** [FossifyOrg/Messages#20]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
Add Fossify SMS Messenger to F-Droid

**Describe the solution you'd like**
Add Fossify SMS Messenger to F-Droid

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by naveensingh** [comment]
@jahway603 https://github.com/FossifyOrg/SMS-Messenger/discussions/18

**Comment by naveensingh** [comment]
@jahway603 please do not create this issue again. F-Droid related discussion is [here](https://github.com/orgs/FossifyOrg/discussions/9) if you want to ask something.
