### ISSUE TITLE
[Feature Request] Advanced Search Features in Global or Individual search (inside a conversation)

### ISSUE THREAD

**Issue by mahdiaqallal** [FossifyOrg/Messages#205]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

It's a GREAT App !
Individual search inside a conversation is not yet implemented, see #49 

Either Individual search inside a conversation or the existing Global might both benefit from advanced search features:
- search by phone number
- search by name = sourced from Android's Contact ID user's Address Book
- select from a date/time range (start - end)
- allowing regular expressions in the search
- allow for fuzzy search (and having in settings a toggle on/off switch for it)
- search / sort conversations from the busiest (=most messages exchanged) to the rarest (=least messages exchanged)

### Why do you want this feature?

Searching in global and individual conversations with tose features will refine and facilitate many more searches than available now. It will also speed things up, as there will be far fewer messages to search through and search attempts. It allow for more criteria to use

### Additional information

None

**Comment by naveensingh** [comment]
Thanks but I'm closing this as it seems too advanced for this app. 

I might still consider simple regexp search as part of https://github.com/FossifyOrg/Messages/issues/49.
