### ISSUE TITLE
Request To Add Fossify Messages App To Accrescent App Store (accrescent.app)

### ISSUE THREAD

**Issue by mxrksec** [FossifyOrg/Messages#208]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add the Messages app to [Accrescent](https://accrescent.app/)

from the domain page of accrescent it states

> Accrescent is a private and secure Android app store built with modern features in mind. It aims to provide a developer-friendly platform and pleasant user experience while enforcing modern security and privacy practices and offering robust validity guarantees for installed apps.

& It's also different from the rest of open source app stores like F-droid or Aurora Store.
From the site link, it provides the [security features](https://accrescent.app/#features) that the most app store (the open source ones) that's lacking that's hyperlinked in security features.

### Why do you want this feature?

To be more safe and secure when installing apps when you also want the app to be open source and doesn't require an account, except for [developers](https://accrescent.app/docs/guide/getting-started/new-app.html) of course.

### Additional information

[Read this for more information about other open source based app store missing security features compared to accrescent](https://privsec.dev/posts/android/f-droid-security-issues/). Hyperlinked to get the full picture as to why this message is requested directly to developers for approval. It is up to you guys.

**Comment by Aga-C** [comment]
See: https://github.com/orgs/FossifyOrg/discussions/228.
