### ISSUE TITLE
Timestamps do not correspond to device time

### ISSUE THREAD

**Issue by WebworkrNet** [FossifyOrg/Messages#219]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 14, One UI 6.1

### Affected device model

Samsung Galaxy A13 5G (SM-A136B)

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

There is a conversation with several messages from both participants.

### Expected behavior

The date and time of the received and sent message is displayed individually and correctly.

### Actual behavior

Messages are summarized under one time stamp.

### Additional information

There may be a discrepancy between the device time and the time server used by the SMS provider.

**Comment by Aga-C** [comment]
What was the time interval between these messages?

**Comment by WebworkrNet** [comment]
> What was the time interval between these messages?

This can no longer be traced in detail, especially as the device at the time recently "crashed". It must have been a few minutes, as far as I can roughly remember.
However, I no longer consider a deviation of even one minute to be acceptable because the time is then no longer correct.

**Comment by Aga-C** [comment]
Seeing your original issue, it seems like a proper app behavior - the app doesn't show a timestamp for each message if they were sent in a span of 5 minutes. However,  if you go into message details, you can see a detailed timestamp. 

If you'll be able to show in the latest version of the app, that two messages were shown under the same timestamp when they were sent in a span larger than 5 minutes, I can reopen this issue.
