### ISSUE TITLE
Link Preview Functionality in Fossify Messages

### ISSUE THREAD

**Issue by T3kn3vra** [FossifyOrg/Messages#227]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

One feature that I find INCREDIBLY useful in other messaging apps, such as:

 Apple iMessage, 

Google Messages, 

WhatsApp, 

etc. 

is the ability to generate a link preview when a user shares a URL. 

This feature enriches the messaging experience by providing a visual and informative snippet of the content behind the link, allowing users to quickly assess its relevance and context before clicking.

### Why do you want this feature?

-/Enhanced User Experience: Link previews provide users with a quick glance at the content, making conversations more engaging and informative.

- Increased Security: By displaying a preview, users can better judge the legitimacy and safety of a link before clicking.

- Improved Aesthetics: Visual previews make messages more visually appealing and organized.

- Time Efficiency: Users can decide whether to engage with the content without needing to leave the app, saving time and effort.

- Contextual Understanding: Link previews offer additional context, helping users understand the subject matter of the link within the flow of conversation.

- Encourages Engagement: Attractive previews can stimulate curiosity and encourage users to click on links they might otherwise overlook.

- Facilitates Sharing: Users are more likely to share links if they know recipients will see a preview, enhancing the sharing experience.

- Reduces Miscommunication: By providing a snapshot of the content, link previews can help reduce misunderstandings about the nature of shared links.

### Additional information

SUGGESTED IMPLEMENTATION:

- Automatic Generation: When a user pastes a link into the chat, Fossify Messages could automatically generate a preview, including a thumbnail image, title, and brief description.

- Toggle Option: Allow users to enable or disable link previews in their settings for greater control over their messaging experience.

- Compatibility: Ensure the feature supports a wide range of websites and platforms to maximize its utility.

I personally believe that adding a link preview feature would GREATLY enhance the overall functionality and appeal of Fossify Messages, aligning it more closely with the capabilities offered by other leading messaging apps. 

_______________________________________
LINKS:

WHAT YOU NEED TO KNOW ABOUT SMS LINK PREVIEWS:
https://simpletexting.com/blog/sms-link-previews/

SMS LINK PREVIEWS: A DETAILED LOOK:
https://www.messageflow.com/blog/sms-link-previews-a-detailed-look

HOW TO TURN ON LINK PREVIEWS IN SIGNAL (OR TURN THEM OFF):
https://www.howtogeek.com/708607/how-to-turn-on-link-previews-in-signal-or-turn-them-off/

**Comment by Aga-C** [comment]
By the design, app has no Internet access, so we can't do this.
