### ISSUE TITLE
Change default camera/voice recorder/file manager in the attachments section.

### ISSUE THREAD

**Issue by joshvala** [FossifyOrg/Messages#229]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Allow changing default apps that are accessed in app if possible.

### Why do you want this feature?

I dont use the apps that it directs me to, so the app is hard to use when sending attachments

### Additional information

Im on samsung android 14 latest version of app.

**Comment by Aga-C** [comment]
Your system is responsible for this. In system settings, you have to find the app that opens by default, and there should be `Open by default` - go there and tap `Clear default preferences`.
