### ISSUE TITLE
Option to change behaviour of the "back" button when opening a message from notification

### ISSUE THREAD

**Issue by nathanzachary** [FossifyOrg/Messages#240]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

When a notification of a new SMS is received and subsequently tapped, it opens the message in Fossify Messages (as intended).  However, after viewing the message, pressing the "back" button completely exits the application.  It would be nice to have an option where pressing the "back" button returns to the message list instead of exiting the app.

### Why do you want this feature?

The option to return to the message list would allow for deleting the message more promptly.  A particular use case here is receiving a text message as part of multi-factor authentication (MFA).  When such a message is received, I prefer to delete them after using the provided MFA code.  Using the "back" button to take me from the notification directly back to the message list would save the step of reopening the app.

**Comment by Aga-C** [comment]
We already have a request to enforce back button to always return to the conversation list: https://github.com/FossifyOrg/Messages/issues/80.

> When such a message is received, I prefer to delete them after using the provided MFA code. Using the "back" button to take me from the notification directly back to the message list would save the step of reopening the app.

You can delete a message without going back to the conversation list.

**Comment by nathanzachary** [comment]
I had see #80, but I didn't think that it directly applied here.  I apologise for my oversight and thank you for looking into the request.

**Comment by eXense-auth** [comment]
- I open the message from the notification
- I try to return to the main screen of the app to delete chats from other senders, but the app closes
- i return to the app through the recent apps menu and opens the last open chat which also closes without letting to get to the main screen with the list of chats
- i delete the open chat and the app closes again, when i try to return through the recent apps menu a blank screen flashes and the app closes immediately
