### ISSUE TITLE
Automatically Copy OTP to Clipboard

### ISSUE THREAD

**Issue by rmj-maker** [FossifyOrg/Messages#248]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [x] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Automatically Copy OTP to Clipboard

### Why do you want this feature?

It's easy to paste the OTP into any login form if it's already copied to the clipboard. One step reduced from the whole login process.

**Comment by Aga-C** [comment]
Do you mean a button on the notification to copy OTP?

**Comment by naveensingh** [comment]
Closing because this will make it _easier_ to steal OTPs and the copy button in the notification seems enough as far as convenience goes.
