### ISSUE TITLE
Some sender SMSs not being received - eg github login 2fa 

### ISSUE THREAD

**Issue by rogercreagh** [FossifyOrg/Messages#254]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 12

### Affected device model

Blackvirw BV7100

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Install app
2. Disable Google messages app and make this one default
3. Receive test SMS from contact ok
4. Attempt to login to a site (eg Coop Bank or GitHub specifically) which sends sms code ad 2FA

### Expected behavior

SmS with 2FA code should be receivedrecieved as normal

### Actual behavior

No SMS recieved.
Re-enable google messages and make default and try again - SMS received and displayed by google app but not by  this one.

Messages from genuine mobile numbers are received ok, but  not ones from websites using sms for 2fa

**Comment by Aga-C** [comment]
Have you set something in `Manage blocked numbers` or `Manage blocked keywords`?

**Comment by rogercreagh** [comment]
> Have you set something in `Manage blocked numbers` or `Manage blocked keywords`?

Not as far as I can see - all is default as when installed. It has imported some blocked numbers - these are the same as in google messages which gets the texts ok.

It as if the app is automatically and silently rejecting from numbers that aren't regular telphone/mobile numbers which I think is the case for many do-not-reply numbers used by these sorts of services sending a one time access code.

**Comment by rogercreagh** [comment]
This has become a complete pain and is making the app unusable since it can't reliably receive important texts. (I lost another notification today). They are received perfectly ok in google's massages app if it is the default, but not at all using this app. The lost ones don't even appear in the google app when it is made default again so it is as if they were never recieved. 

So far it only seems to mostly affect messages with security codes, although today's was from Screwfix notifying that a click and collect item was ready.. 

Since it works fine with google's app I don't see how it can be a phone problem. There is nothing obvious anywhere in the settings (I've been all through the phone and app settings). Is google somehow blocking other apps from accessing these messages upstream of the messaging apps? Does no-one else have this problem?

If google is the default SMS app and it receives one, then when I open this app (it seems both this and the google app will only open if they are the default sms app) they appear in the app after a short delay. Since the whole point of using this app is to replace the google one, it makes no sense to be having to constantly remember to change the default back to google when closing the app so that messages don't get lost.

Security codes are these days the most common and most important texts that I get - even github is using them. They are a right royal pain, but that's another story - for now they are just a part of the shitification of technology.

In all other respects the app works fine, but this makes it unusable.

**Comment by naveensingh** [comment]
@rogercreagh 

Since you have a BlackView phone, could you please try the solution mentioned in [this other related issue](https://github.com/FossifyOrg/Messages/issues/266#issuecomment-2564287496)?

**Comment by rogercreagh** [comment]
YAY!!! :-) Many thanks @naveensingh That Works.

Had completely forgotten about the BV System Manager App. Incidentally the Fossify Messages app is simply called "Messages" in my phone - distinguished from the google one by a green icon instead of a blue one.
