### ISSUE TITLE
Does not run at startup: no sms are received unless messages is started

### ISSUE THREAD

**Issue by Wanou38** [FossifyOrg/Messages#266]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 11

### Affected device model

Blackview BV6600 pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open the fossify messenger app
2. Send a test sms to the phone with the text "opened app"
3. Close the messenger app
4. Send a test sms to the phone with the text "closed app"

### Expected behavior

Both SMS are received

### Actual behavior

Only "opened app" SMS is received

### Additional information

"run at startup" permission seem missing in the list on F-Droid store. Some other sms apps have it so it may explain why this happens to me.

**Comment by Aga-C** [comment]
Do you see both messages after entering the app?

**Comment by Wanou38** [comment]
No, the "closed app" message is lost.

**Comment by antodc** [comment]
@Wanou38 I have a Oscal phone, which is kind of a cheaper brand of Blackview. I have to put the Message app in the white list of the System Management app. Maybe you can try doing the same, if you did not already.

**Comment by Wanou38** [comment]
In the battery optimization menu, the "Fossify messages" app can't be optimized so it should not be doze by system.
But, when issuing `adb shell dumpsys deviceidle whitelist`, `org.fossify.messages` is not in the list.
I don't known how i can put it in in the list without root privileges

**Comment by antodc** [comment]
@Wanou38 Do you have a System Manager app on your phone? It has an icon with a shield. If yes, open that app, select 'App management' and then select Fossify Messages in the 'Auto Start Management' and 'Auto cleanup' sections. No root permissions are required.
If you do not have any System Manager app, forget my messages.

**Comment by Wanou38** [comment]
I don't have a system manager app or any app that allow managing auto start or cleanup.
I also looked if the issue was not caused by others apps. Blokada and "yet another call blocker" have been uninstalled, with no success so far.

**Comment by antodc** [comment]
Sorry if I ask you, but is there any chance that you hid/deactivated it? My understanding is that System Manager is preinstalled on Blackview devices.

**Comment by Wanou38** [comment]
> @Wanou38 Do you have a System Manager app on your phone? It has an icon with a shield. If yes, open that app, select 'App management' and then select Fossify Messages in the 'Auto Start Management' and 'Auto cleanup' sections. No root permissions are required. If you do not have any System Manager app, forget my messages.

I finally discovered the system manager on my android 11 phone and the trick works. I still have two android 10 devices where no

**Comment by antodc** [comment]
Very glad to know!! 😉
Just found out this article (https://dontkillmyapp.com/blackview). It claims the ‘solutions’ should work with Android 10, but no idea whether it is indeed true.

**Comment by Wanou38** [comment]
@antodc Your link was usefull to fix the issue with a BV4900 (android 10), by whitelisting the message app

With a BV Tab8 (android 10), the "autorun" and "close app on lock" were in the battery settings.

**Comment by naveensingh** [comment]
On AOSP like ROMs, default Phone & SMS apps have zero battery restrictions.

There is a `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission that we can use to request unrestricted background activity but if memory serves me right, apps have been suspended for using that. It probably won't have any effect on these devices anyway. 

Closing this as it is more or less already resolved.

**Comment by Wanou38** [comment]
The query was not to add `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS`  but to run it at startup and add it to the whitelist of apps that system should not stop.
Without these settings, Fossify messages is useless.

In many apps, like `Fair email` or 'DAVx5', the app check these settings and help the user to fix the issues, indicating what's wrong.

So, if no changes are made to the app to require things that could make troubles with google, users need at least some help.

**Comment by naveensingh** [comment]
My point was that there is no way official permission that we could request or action that we could trigger to add the app to the whitelist. The app-killing-optimizers differ from vendor to vendor.

Whenever you receive a message, the system is supposed to start the Messages app with "hey, here's a new message, do what you want" but in your case, the system doesn't seem to do so. 

I have created a general issue to add a new FAQ entry for this: https://github.com/FossifyOrg/General-Discussion/issues/268
