### ISSUE TITLE
move settings button inside dot menu

### ISSUE THREAD

**Issue by 3zSup** [FossifyOrg/Messages#268]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Title. (Move settings icon inside drop menu)

### Why do you want this feature?

Some buttons are not the same across all apps, which is strange because the settings button is inside the dot menu in (e.g. Phone app) , while in Messages it is outside for some reason?

**Comment by Aga-C** [comment]
Please fill out the form properly.

**Comment by 3zSup** [comment]
The Feature description is already in the title whats the issue aside from that?

**Comment by naveensingh** [comment]
Should be fixed in the next update.

**Comment by 3zSup** [comment]
I wanted to add that this happens on other apps too like voice recorder. There is no drop menu instead 2 icons one for settings one for the about page.

**Comment by naveensingh** [comment]
Yeah, it'll be moved back into the menu in future updates.

**Comment by 3zSup** [comment]
Thanks for updating recorder and messages this shows up on file manager too under the storage menu

**Comment by naveensingh** [comment]
It'll be done in all apps when they are updated.
