### ISSUE TITLE
addition of "Sync Messages" button in the settings

### ISSUE THREAD

**Issue by Abcd1234-dot** [FossifyOrg/Messages#28]
**Is your feature request related to a problem? Please describe.**
I am using stock android 8.1 and many times the new messages don't get loaded automatically although it is already received by device. Later I found out it is a sync issue with native android SMS database.

**Describe the solution you'd like**
It would be convenient to have a sync button within the app settings which can sync manually with native android sms data base. QK-SMS app has this functionality.

**Comment by Aga-C** [comment]
The app is synchronized with the native SMS database, so there is no need for any manual sync button. If you have issues with synchronization, please raise a bug.
