### ISSUE TITLE
Read me my texts!

### ISSUE THREAD

**Issue by Spike-from-NH** [FossifyOrg/Messages#3]
(Was №794 of Simple Messenger)

Many years ago, I had a non-Android flip-phone that had a text-to-speech user preference. Since moving to Android, I have never found a way to command any SMS app, including Messenger, to pass incoming texts to TTS. When driving, with the phone in the "hands-free" holster required by local law, I'd prefer to hear every SMS immediately when it's received. Otherwise, even such an option on the long-press message menu would be welcome. (I imagine it would be "marked as read" after being read TO me.)

**Comment by naveensingh** [comment]
@Spike-from-NH Please follow the feature request [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by Aga-C** [comment]
@Spike-from-NH I am closing this issue because it didn't comply with old issue template, wasn't fixed and some time ago we've moved to issue forms. If you still want this issue to be open, please raise a new issue with a properly filled form.
