### ISSUE TITLE
Import & Export blocked keywords

### ISSUE THREAD

**Issue by furuycom** [FossifyOrg/Messages#37]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
The app has "import & export blocked numbers" features in the "blocked numbers" settings, but this feature is missing in the "blocked keywords" settings.

**Describe the solution you'd like**
Add "import & export blocked keywords" features in the "blocked keywords" settings.

**Comment by ronniedroid** [comment]
I will work on this next week hopefully.

**Comment by vertigo220** [comment]
Ideally it should just have a main import/export setting that allows selecting which aspects (messages, keywords, etc) to import/export, and, if possible, it should keep all this info in a file that can be sync'd with an external program.
