### ISSUE TITLE
Theme isn't applying on the Action Bar.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [FossifyOrg/Messages#38]
**Checklist**
 - [✅] I can reproduce the bug with the latest version. 
 - [✅] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [✅]  I have read the FAQ and my problem isn't listed.
 - [✅]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [✅]  This issue contains only one bug.
 - [✅]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
Whenever you long-press on a message or conversation, an Action Bar appears. But the problem is that the bar doesn't follow the custom theme chosen by the user. So, please fix this.

**To Reproduce**
1. Open Fossify Messages app.
2. Long-press on any conversation, then notice the Action Bar.
3. Open any conversation & long-press any message, then notice the Action Bar.

Note: Before following above steps, you should already be using a pure black AMOLED Theme like me.

**Expected behavior**
Whatever colour user has chosen in "Background Colour" & "Primary Colour" should also get applied to the Action Bar.

**Screenshots**
![Screenshot_2024-01-23-07-24-50-57_f3369ad6253aa3dfe04568d105f6ea48](https://github.com/FossifyOrg/Messages/assets/91815107/fc346de2-61f9-46a4-b0c0-f6e1ebfaa25e)
![Screenshot_2024-01-23-07-26-42-19_f3369ad6253aa3dfe04568d105f6ea48](https://github.com/FossifyOrg/Messages/assets/91815107/21c4ea41-2443-4f5a-a5b5-27d4dc3f1cb0)

**Device info (please complete the following information):**
 - Model: Realme 7 Pro
 - OS: Android 12 (skin name is RUI 3.0)
 - App version: v1.0.0

**Additional context**
Not really, wrote everything above.

**Comment by Aga-C** [comment]
Please raise issues regarding all apps in https://github.com/FossifyOrg/General-Discussion/issues.
