### ISSUE TITLE
Typing cursor

### ISSUE THREAD

**Issue by zorzibaffo** [FossifyOrg/Messages#39]
When phone goes into sleep mode while writing a message, typing cursor goes back to the beginning of the message.

Maybe this could be improved.

Many thanks for this app/fork.

Dearly.

**Comment by Aga-C** [comment]
Please adjust your bug report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Aga-C** [comment]
@zorzibaffo I am closing this issue because it didn't comply with old issue template, wasn't fixed and some time ago we've moved to issue forms. If you still want this issue to be open, please raise a new issue with a properly filled form.
