### ISSUE TITLE
Lock-screen preference also affects notification

### ISSUE THREAD

**Issue by Spike-from-NH** [FossifyOrg/Messages#4]
(Was №791 of Simple Messenger)

When the setting "Lock screen notification visibility" is set to "Nothing", it also results in an empty notification in the windowshade and inhibits the medallion on the home-page icon. If you meant this setting to have all these effects, at least reword the prompt.

Observed on Samsung J3 with Android 9 and Samsung J7 with Android 8, Messenger 5.19.3.
Initially reported and misdiagnosed in [№765 of Simple Messenger].
Low priority; obvious workaround.

**Comment by naveensingh** [comment]
@Spike-from-NH Please follow the bug report [issue template](https://raw.githubusercontent.com/FossifyOrg/SMS-Messenger/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Aga-C** [comment]
@Spike-from-NH I am closing this issue because it didn't comply with old issue template, wasn't fixed and some time ago we've moved to issue forms. If you still want this issue to be open, please raise a new issue with a properly filled form.

**Comment by Spike-from-NH** [comment]
No, I shall not. I did you the favor of copying over my bug reports to Simple Mobile Tools before you forked a copy, and your response was to refuse to look at them until I fill out your picky form certifying that I am not wasting your time! I urge you to import all the open issues from all the SMT projects you forked, taking prior owner's decision to keep them open as reviewed evidence there are bugs in the code you took over, or reasonable requests for new features.
