### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by xmha97** [FossifyOrg/Messages#43]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Please add the markdown support (like WhatsApp)

**Comment by Aga-C** [comment]
Please fill out the template more descriptive. Especially, the reason - why do you need markdown in SMS messages?

**Comment by kekkoudesu** [comment]
SMS doesn't support bold/italics...right? So even if Fossify Messages supported it, the recipient's SMS client wouldn't render it.

I guess it *might* make sense to interpret a word surrounded in asterisks to mean *italicized*, and double asterisks to mean **bolded**, but that's only markdown support for the Fossify Messages side, and doesn't make much sense to me.

**Comment by Aga-C** [comment]
@xmha97 I am closing this issue because it didn't comply with old issue template, wasn't fixed and some time ago we've moved to issue forms. If you still want this issue to be open, please raise a new issue with a properly filled form.
