### ISSUE TITLE
"Trash can" icon nearly invisible if new text arrives

### ISSUE THREAD

**Issue by Spike-from-NH** [FossifyOrg/Messages#5]
(Was №606 of Simple Messenger—look there for screenshots.)
(Last of three issue imports for me.)

Icon colors generally have good contrast to the background color—but here's a fleeting bug.

➊ Phone A texts phone B.
➋ I tap the notification on B, bring up Messenger. Background of header* and message area are my chosen pastel color, trash can is black, good.
➌ I long-press the new message. Header turns black, icons turn white, good.
➍ A texts B again. First text is still selected but trash can is now dark gray on black and nearly invisible. That's the bug. (After typing this item and switching back to Messenger, trash can is white again. A third text and trash can is gray again. You can still press trash can and it reverts to white, though the entire screen dims in favor of the confirmation pop-up.)
➎ After deleting one of these test texts, trash can is white (on same pastel background; bad). Other icons are black on pastel, good. Again, switching to browser to type this then switching back to Messenger, all icons are black on pastel.

Found this bug when texting for a report and preparing to delete a previous report—after comparing it to the fresh report.

*Separate observation: When viewing a thread from one texter, it would better distinguish the header from the list if the header background were the chosen "primary color" rather than "background color".

**Comment by naveensingh** [comment]
@Spike-from-NH Please follow the bug report [issue template](https://raw.githubusercontent.com/FossifyOrg/SMS-Messenger/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Aga-C** [comment]
@Spike-from-NH I am closing this issue because it didn't comply with old issue template, wasn't fixed and some time ago we've moved to issue forms. If you still want this issue to be open, please raise a new issue with a properly filled form.
