### ISSUE TITLE
Sending group message in existing group sends individual message to each recipient

### ISSUE THREAD

**Issue by bryonadams** [FossifyOrg/Messages#50]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 11

### Affected device model

Motorola G Stylus 2021

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

1. Have existing group message (I had one started from Google Messages & QKSMS already)
2. Send message to group from Fossify Messages
3. View messages in another app or start a new message to individual contacts from Fossify Messages, there will be an individual message to each contact.

### Expected behavior

Message stays within group message thread rather than individiaul messages

### Actual behavior

Individual message sent to each contact.

### Additional information

There is a "group message as MMS" setting that is disabled by default but I don't know if that's required or not. I don't have a similar setting in QKSMS.

**Comment by Aga-C** [comment]
Please enable the `Send group messages as MMS` option, send the message to the group, and check if this time the message appears only in the group conversation.

**Comment by bryonadams** [comment]
Hi Aga-C, it looks like that works. Perhaps this should be enabled by default? I can see someone wanting the option to use either method.

**Comment by Aga-C** [comment]
I remember that in Simple Mobile Tools it was requested by people to work like this because in many countries MMS are more expensive (sometimes they have free SMS and paid MMS), and it was misleading for people that they have to pay after sending a group message when they haven't added anything despite text.

**Comment by bryonadams** [comment]
I'll open a feature request for this then, because it's also misleading to have group messages to not actually work as a group message. I do understand that what I'd like would be undesirable for others though.

**Comment by m-fonseca** [comment]
FWIW, this has bitten me a number of times when sending to a group;  everyone texts me back and tells me I didn't send it to the group.  I didn't realize this option was there.  I'm not sure how you handle a default to make everyone happy (perhaps making the user aware of it during install?).

**Comment by bryonadams** [comment]
There's a feature request I submitted here:

https://github.com/FossifyOrg/Messages/issues/52#issue-2102481324

**Comment by naveensingh** [comment]
There's an [FAQ entry](https://github.com/FossifyOrg/Messages/pull/543) for this now.
