### ISSUE TITLE
[Feature request] End-to-end SMS encryption

### ISSUE THREAD

**Issue by Atrate** [FossifyOrg/Messages#62]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

In the interest of security, it's be nice to have the ability to have end-to-end encryption for SMS messages. There's various apps that perform E2EE via the network, but (with the exception of Silence, which is abandoned) there's no app as far as I know that lets you encrypt SMS messages.

Of course, it'd require the other person to also have the same application, but that's the way it usually is with any kind of encryption regardless.

### Why do you want this feature?

As of January 2024, there are no SMS apps for Android that:
1. Support E2E Encryption via SMS
2. Are actively maintained (Silence does not work on the newest Android devices and never will, and it has probably accumulated a plethora of security vulnerabilities in the past couple of years)

### Additional information

Silence source code: https://git.silence.dev/Silence/Silence-Android/

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/27.
