### ISSUE TITLE
Auto-set conversation name based on rules

### ISSUE THREAD

**Issue by vertigo220** [FossifyOrg/Messages#74]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Use keywords to set a conversation name, e.g. if a message contains "Your Amazon package with" OR "Details amzn(dot)com/orders" rename the conversation automatically from ###### to Amazon.

### Why do you want this feature?

To make it more clear who texts are from by automatically replacing (or appending) the numbers with a user-customizable name based on text content.

**Comment by Aga-C** [comment]
It's too advanced for the regular SMS app.  

I doubt people would like to write such rules. On the other hand, if you thought about incorporating such predefined rules into code, there are too many different possibilities, and you'd need to consider different languages. 

You can already rename conversations on your own, it should be enough for most cases.

**Comment by vertigo220** [comment]
Given the app already has keyword functionality for blocking messages, this really wouldn't be adding that much or making it much more advanced, and if some users find it too advanced, 1) they're probably not going to use the blocking feature either, and 2) they don't have to use it. It could also allow sharing of rules, so users could post rules they've created and people that find it too advanced could search and import those.
