### ISSUE TITLE
Couldn't send message, Error Code: 1

### ISSUE THREAD

**Issue by nxjosephofficial** [FossifyOrg/Messages#85]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 14 / HyperOS by xiaomi.eu 1.0.2.0.UMTMIXM Stable

### Affected device model

Redmi Note 12 4G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Click to + icon to send a message
2. Select a contact or write a number
3. Type a message
4. Press Send button
5. Get the error

### Expected behavior

I can't send any messages but i should have be able to.

### Actual behavior

I get the "Couldn't send message, Error Code: 1" error when i try to send a message.

### Screenshots/Screen recordings

<img src="https://github.com/FossifyOrg/Messages/assets/153529729/1c475b65-fb0d-4021-b480-21d9b7a1cd38" width="250">

### Additional information

My phone is rooted with magisk. I uninstalled default Caller, Messaging and Contacts app. I can't get messages too.

**Comment by nxjosephofficial** [comment]
I am tried reinstalling default messaging, contacts and caller app but it didn't work. Now I got error code -3 with some java.lang.securityException errors.

**Comment by Aga-C** [comment]
Does the default messaging app or any other SMS app work? Can you send and receive messages in them?

**Comment by nxjosephofficial** [comment]
I didn't try the default apps. I am using other fossify apps like Caller and Contacts with Messages app. After clearing all of their data and giving them all the permissions they wanted, I was able to send messages but now I still can't get messages.

**Comment by nxjosephofficial** [comment]
I tried default messaging app now and i can send/receive messages.

**Comment by Aga-C** [comment]
Check permissions once again, maybe in system settings. SecurityException suggests that the app lacks the permission to access SMS messages.

**Comment by nxjosephofficial** [comment]
You are right. Although I give all the permissions they wanted by selecting "always give access all the time", I saw that some of their permissions were denied as I see their permissions in system settings app. Thank you very much.

<img src="https://github.com/FossifyOrg/Messages/assets/153529729/26735e32-204c-41bc-967f-8d57a87bdd28" width="250">
<img src="https://github.com/FossifyOrg/Messages/assets/153529729/c15c1f29-0457-4f8d-b979-3f6e8f4e4f57" width="250">

**Comment by hroptatyr** [comment]
I get this error, too, error code: 1 in particular, on a non-rooted Android 13.  The official app (Google's Messages) wouldn't work either.

**Comment by naveensingh** [comment]
> I get this error, too, error code: 1 in particular, on a non-rooted Android 13. The official app (Google's Messages) wouldn't work either.

Sounds like a network or configuration issue. Error code 1 means a generic failure, so it could be anything.

**Comment by hroptatyr** [comment]
I got Google Messages working now. I think Fossify Messages is using the wrong SMSC.

**Comment by naveensingh** [comment]
It must be something else because SMSC isn't set per-app.
