### ISSUE TITLE
MMS picture text returns Error Code #5

### ISSUE THREAD

**Issue by jacorizla** [FossifyOrg/Messages#91]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

android 10 - 8A.0.10-19-10.0.0-10.34.03

### Affected device model

Sonim XP8800

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

Open app
Select contact
select "take photo"
Hit send
"Not sent. Touch to retry."
Sometimes there's a popup that says Error.Code 5

### Expected behavior

Send a photo text via mms

### Actual behavior

Nothing sent

**Comment by Aga-C** [comment]
Check in-app FAQ, first entry. Does it help?

**Comment by jacorizla** [comment]
Reducing MMS size limit fixed this.

**Comment by jacorizla** [comment]
Reducing the MMS limit fixed the issue.

**Comment by jacorizla** [comment]
> Check in-app FAQ, first entry. Does it help?

Yes. Thank you.
