### ISSUE TITLE
Enabling Delivery Report Does Nothing

### ISSUE THREAD

**Issue by HonestAbe7** [FossifyOrg/Messages#94]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 10

### Affected device model

LG355DL

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to setting
2.  Scroll down and check "Enable delivery reports"

### Expected behavior

I was expecting a separate message saying "Delivered" or something.

### Actual behavior

The check mark indicating it is sent still appears even if I umcheck it in settings. What is the point of the checkmark? Can this setting be deleted as the checkmark indicates message sent?

**Comment by Aga-C** [comment]
Check means that the message is sent. If delivery reports are enabled, there can appear the second check that means delivered.

**Comment by HonestAbe7** [comment]
OK. No second message at all for me.
