### ISSUE TITLE
First message hidden

### ISSUE THREAD

**Issue by Mylloon** [FossifyOrg/Messages#96]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 13 / Miui 14.0.3

### Affected device model

Xiaomi Redmi Note 13

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Go to a conversation
2. Look at the first message
3. Message isn't here

### Expected behavior

First message should be shown

### Actual behavior

First message is hidden

### Additional information

There is a little short time when I see it dissapear

**Comment by Aga-C** [comment]
Do other messaging apps show this message? Isn't this message deleted by another app?

**Comment by Mylloon** [comment]
I have no other sms app, but I just installed [Connect You](https://github.com/you-apps/ConnectYou) and [QKSMS](https://github.com/moezbhatti/qksms) and both are not showing the message

So, the message is only in Fossify Message and not in the others

**Comment by Aga-C** [comment]
Can you fully uninstall and then reinstall Fossify Messages, and check if you still have this disappearing message?

**Comment by Mylloon** [comment]
The message disappeared, I don't know why the message was a ghost I never deleted it

**Comment by Aga-C** [comment]
Ok, so probably the message was somehow broken that other apps didn't see it. Fossify Messages could originally copy and cache it, that's why it was visible for a while. I close this problem as resolved.
