### ISSUE TITLE
Uniting name - repository vs app name

### ISSUE THREAD

**Issue by inson1** [FossifyOrg/Messages#97]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Repository: "Messages"
App name: "SMS Messenger"

### Why do you want this feature?

Why have 2 names?

### Additional information

If you dont agree please move to discussions :)

**Comment by Aga-C** [comment]
This is temporary, app name will be changed.

**Comment by inson1** [comment]
@Aga-C What about keeping this open till the renaming is done?

**Comment by naveensingh** [comment]
@inson1 it's not an 'issue' that needs tracking. The app name will be renamed later.
